"""Initial migration

Revision ID: 04516c9be1e0
Revises: b78d36deb733
Create Date: 2024-12-08 00:11:55.189505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04516c9be1e0'
down_revision: Union[str, None] = 'b78d36deb733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_slug', table_name='users')
    op.create_index(op.f('ix_users_slug'), 'users', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_slug'), table_name='users')
    op.create_index('ix_users_slug', 'users', ['slug'], unique=False)
    # ### end Alembic commands ###
